"""NPSV3 native graph tools"""

from collections.abc import Sequence
import enum
from typing import overload


class KmerZygosity(enum.Enum):
    ABSENT = 0

    HETEROZYGOUS = 1

    HOMOZYGOUS = 2

    FREQUENT = 3

class UniqueKmersOverlay:
    @overload
    def __init__(self, graph: Graph, k: int, max_edges: int = 1000, exclude_universal: bool = True, canonicalize: bool = False, ref_kmer_counts: KmerCounts | None = None) -> None: ...

    @overload
    def __init__(self, graph: Graph, path: str) -> None: ...

    @overload
    def __init__(self, graph: Graph, data: bytes) -> None: ...

    def __len__(self) -> int: ...

    @property
    def sequences(self) -> list[str]: ...

    def locations_as_node_ids(self, graph: Graph) -> list[list[tuple[list[int], int]]]: ...

    def save_fasta(self, fasta_path: str) -> None: ...

    def save(self, path: str) -> None: ...

    def save_bytes(self) -> bytes: ...

class KmerCounts:
    def __init__(self, db_path: str) -> None: ...

    def count(self, kmer: str) -> int: ...

class KmerClassify:
    def __init__(self, db_path: str, coverage: float) -> None: ...

class Diplotype:
    @property
    def haplotypes(self) -> tuple: ...

    @property
    def score(self) -> float: ...

class HaplotypeSamplerOverlay:
    @overload
    def __init__(self, graph: Graph, unique_kmers: UniqueKmersOverlay) -> None: ...

    @overload
    def __init__(self, graph: Graph, unique_kmers: UniqueKmersOverlay, inference_vcf: str, region: Range, min_size: int = 50) -> None: ...

    def initialize_scores(self, counts: KmerClassify) -> None: ...

    def sample_haplotypes(self, n: int) -> list[list[int]]: ...

    def find_best_paths(self, n: int) -> list[list[int]]: ...

    def sample_diplotypes(self, candidates: Sequence[Sequence[int]], n: int) -> list[Diplotype]: ...

    def score(self, haplotype: Sequence[int]) -> float: ...

    def decode_haplotype(self, haplotype: Sequence[int]) -> list[tuple[str, int]]: ...

    def num_kmers(self) -> int: ...

    def kmers_on_path(self, path: Sequence[int]) -> list[int]: ...

    def kmer_score_at(self, idx: int) -> float: ...

    def kmer_sequence_at(self, idx: int) -> str: ...

class Range:
    @overload
    def __init__(self, arg0: str, arg1: int, arg2: int, /) -> None: ...

    @overload
    def __init__(self, region: str) -> None: ...

    @staticmethod
    def parse_literal(region: str) -> Range: ...

    @staticmethod
    def parse_slug(slug: str) -> Range: ...

    @property
    def contig(self) -> str: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def length(self) -> int: ...

    def __len__(self) -> int: ...

    @property
    def center(self) -> Range: ...

    @property
    def pysam_fetch(self) -> dict: ...

    @overload
    def expand(self, arg0: int, arg1: int, /) -> Range: ...

    @overload
    def expand(self, arg: int, /) -> Range: ...

    def union(self, arg: Range, /) -> Range: ...

    def union_with(self, arg: Range, /) -> None: ...

    def intersection(self, arg: Range, /) -> Range: ...

    def overlaps(self, arg: Range, /) -> bool: ...

    def contains(self, point: int) -> bool: ...

    def window(self, size: int) -> list[Range]: ...

    def get_overlap(self, has_region: object) -> int: ...

    def __eq__(self, arg: Range, /) -> bool: ...

    def __le__(self, arg: Range, /) -> bool: ...

    def __lt__(self, arg: Range, /) -> bool: ...

    def __hash__(self) -> int: ...

    @property
    def slug(self) -> str: ...

    def __str__(self) -> str: ...

class Variant:
    @property
    def contig(self) -> str: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def num_alleles(self) -> int: ...

    @property
    def num_alts(self) -> int: ...

    @property
    def ref_length(self) -> int: ...

    @property
    def variant_id(self) -> str: ...

    @property
    def has_star_allele(self) -> bool: ...

    def reference_region(self) -> Range: ...

    def record_reference_region(self) -> Range: ...

    def allele_reference_region(self, arg: int, /) -> Range | None: ...

    def allele_length_change(self, arg: int, /) -> int | None: ...

    def allele_length(self, allele_idx: int) -> int | None: ...

    @overload
    def length_change(self) -> list[int | None]: ...

    @overload
    def length_change(self, allele_idx: int) -> int | None: ...

    def allele(self, allele_idx: int) -> str: ...

    def allele_sequence(self, allele_idx: int) -> str | None: ...

    def info_int(self, key: str) -> list[int] | None: ...

    def is_filtered(self) -> bool: ...

    def set_filter_pass(self) -> None: ...

    def has_passing_genotype(self) -> bool: ...

    def subset_samples(self, arg: Sequence[int], /) -> Variant: ...

    def genotype(self, sample_idx: int) -> tuple: ...

    def __str__(self) -> str: ...

class VariantFileHeader:
    def subset(self, arg: Sequence[str], /) -> VariantFileHeader: ...

class VariantFileReaderIterator:
    def __iter__(self) -> object: ...

    def __next__(self) -> Variant: ...

class VariantFileReader:
    @staticmethod
    def open(arg: str, /) -> VariantFileReader: ...

    def __enter__(self) -> VariantFileReader: ...

    def __exit__(self, exc_type: object | None = None, exc_value: object | None = None, traceback: object | None = None) -> bool: ...

    @overload
    def fetch(self) -> VariantFileReaderIterator: ...

    @overload
    def fetch(self, region: Range | None = None) -> VariantFileReaderIterator: ...

    def samples(self) -> list[str]: ...

    def header(self) -> VariantFileHeader: ...

    def close(self) -> None: ...

class VariantFileWriter:
    @staticmethod
    def open(filename: str, header: VariantFileHeader, format: str | None = None) -> VariantFileWriter: ...

    def write(self, arg: Variant, /) -> None: ...

    def close(self) -> None: ...

class Graph:
    def __init__(self, arg0: str, arg1: str, arg2: Range, /) -> None: ...

    def save(self, path: str) -> None: ...

    def save_bytes(self) -> bytes: ...

    @staticmethod
    def load(path: str) -> Graph: ...

    @staticmethod
    def load_bytes(data: bytes) -> Graph: ...

    def node_count(self) -> int: ...

    def has_path(self, arg: str, /) -> bool: ...

    def path_nodes(self, arg: str, /) -> list[int]: ...

    def samples_including(self, arg: Sequence[int], /) -> list[str]: ...

    def dump(self) -> None: ...

    def path_sequence(self, nodes: Sequence[int]) -> str: ...

    def haplotype_paths(self, prefix: str) -> list[int]: ...
