"""NPSV3 native graph tools"""

from collections.abc import Sequence
import enum
from typing import overload


class KmerZygosity(enum.Enum):
    ABSENT = 0

    HETEROZYGOUS = 1

    HOMOZYGOUS = 2

    FREQUENT = 3

class UniqueKmersOverlay:
    @overload
    def __init__(self, graph: Graph, k: int, max_edges: int = 1000, exclude_universal: bool = True, canonicalize: bool = False, ref_kmer_counts: KmerCounts | None = None) -> None: ...

    @overload
    def __init__(self, graph: Graph, path: str) -> None: ...

    @overload
    def __init__(self, graph: Graph, data: bytes) -> None: ...

    @overload
    def __init__(self, graph: Graph, data: bytearray) -> None: ...

    def __len__(self) -> int: ...

    @property
    def sequences(self) -> list[str]: ...

    def locations_as_node_ids(self, graph: Graph) -> list[list[tuple[list[int], int]]]: ...

    def save_fasta(self, fasta_path: str) -> None: ...

    def save(self, path: str) -> None: ...

    def save_bytes(self) -> bytearray: ...

class KmerCounts:
    def __init__(self, db_path: str) -> None: ...

    def count(self, kmer: str) -> int: ...

class KmerClassify:
    def __init__(self, db_path: str, coverage: float) -> None: ...

class ConstantKmerClassify(KmerClassify):
    def __init__(self, zygosity: KmerZygosity = KmerZygosity.HOMOZYGOUS) -> None: ...

class PanelState:
    pass

class HaplotypePriorOverlay:
    @overload
    def __init__(self, graph: Graph, excluded_samples: Sequence[str] = []) -> None: ...

    @overload
    def __init__(self, graph: Graph, path: str) -> None: ...

    @overload
    def __init__(self, graph: Graph, data: bytes) -> None: ...

    @overload
    def __init__(self, graph: Graph, data: bytearray) -> None: ...

    def find(self, node: int) -> PanelState: ...

    def extend(self, state: PanelState, node: int) -> PanelState: ...

    def empty(self, state: PanelState) -> bool: ...

    def width(self, state: PanelState) -> int: ...

    def score_to_go(self, state: PanelState) -> float: ...

    @property
    def node_totals(self) -> list[int]: ...

    def transition_probability(self, from_node: int, to_node: int, alpha: float) -> float: ...

    def log_transition_probability(self, from_node: int, to_node: int, alpha: float) -> float: ...

    def save(self, path: str) -> None: ...

    def save_bytes(self) -> bytearray: ...

class Diplotype:
    @property
    def haplotypes(self) -> tuple: ...

    @property
    def score(self) -> float: ...

class HaplotypeSamplerOverlay:
    @overload
    def __init__(self, graph: Graph, unique_kmers: UniqueKmersOverlay, prior: HaplotypePriorOverlay | None = None, params: Params | None = None) -> None: ...

    @overload
    def __init__(self, graph: Graph, unique_kmers: UniqueKmersOverlay, inference_vcf: str, region: Range, min_size: int = 50, prior: HaplotypePriorOverlay | None = None, params: Params | None = None) -> None: ...

    class Params:
        @overload
        def __init__(self) -> None: ...

        @overload
        def __init__(self, homozygous_score: float = 1.0, absent_score: float = -0.8, heterozygous_score: float = 0.0, homozygous_discount: float = 0.9, het_adjustment: float = 0.05, haplotype_prior_weight: float = 0.0, panel_fallback_penalty: float = 0.0, transition_prior_alpha: float = 1.0, population_state_pool_cap: int = 8) -> None: ...

        @property
        def homozygous_score(self) -> float: ...

        @homozygous_score.setter
        def homozygous_score(self, arg: float, /) -> None: ...

        @property
        def absent_score(self) -> float: ...

        @absent_score.setter
        def absent_score(self, arg: float, /) -> None: ...

        @property
        def heterozygous_score(self) -> float: ...

        @heterozygous_score.setter
        def heterozygous_score(self, arg: float, /) -> None: ...

        @property
        def homozygous_discount(self) -> float: ...

        @homozygous_discount.setter
        def homozygous_discount(self, arg: float, /) -> None: ...

        @property
        def het_adjustment(self) -> float: ...

        @het_adjustment.setter
        def het_adjustment(self, arg: float, /) -> None: ...

        @property
        def haplotype_prior_weight(self) -> float: ...

        @haplotype_prior_weight.setter
        def haplotype_prior_weight(self, arg: float, /) -> None: ...

        @property
        def panel_fallback_penalty(self) -> float: ...

        @panel_fallback_penalty.setter
        def panel_fallback_penalty(self, arg: float, /) -> None: ...

        @property
        def transition_prior_alpha(self) -> float: ...

        @transition_prior_alpha.setter
        def transition_prior_alpha(self, arg: float, /) -> None: ...

        @property
        def population_state_pool_cap(self) -> int: ...

        @population_state_pool_cap.setter
        def population_state_pool_cap(self, arg: int, /) -> None: ...

    def initialize_scores(self, counts: KmerClassify) -> None: ...

    def sample_haplotypes(self, n: int) -> list[list[int]]: ...

    def find_best_paths(self, n: int) -> list[list[int]]: ...

    def sample_diplotypes(self, candidates: Sequence[Sequence[int]], n: int) -> list[Diplotype]: ...

    def score(self, haplotype: Sequence[int]) -> float: ...

    def decode_haplotype(self, haplotype: Sequence[int]) -> list[tuple[str, int]]: ...

    def num_kmers(self) -> int: ...

    def kmers_on_path(self, path: Sequence[int]) -> list[int]: ...

    def kmer_score_at(self, idx: int) -> float: ...

    def kmer_sequence_at(self, idx: int) -> str: ...

class Range:
    @overload
    def __init__(self, arg0: str, arg1: int, arg2: int, /) -> None: ...

    @overload
    def __init__(self, region: str) -> None: ...

    @staticmethod
    def parse_literal(region: str) -> Range: ...

    @staticmethod
    def parse_slug(slug: str) -> Range: ...

    @property
    def contig(self) -> str: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def length(self) -> int: ...

    def __len__(self) -> int: ...

    @property
    def center(self) -> Range: ...

    @property
    def pysam_fetch(self) -> dict: ...

    @overload
    def expand(self, arg0: int, arg1: int, /) -> Range: ...

    @overload
    def expand(self, arg: int, /) -> Range: ...

    def union(self, arg: Range, /) -> Range: ...

    def union_with(self, arg: Range, /) -> None: ...

    def intersection(self, arg: Range, /) -> Range: ...

    def overlaps(self, arg: Range, /) -> bool: ...

    def contains(self, point: int) -> bool: ...

    def window(self, size: int) -> list[Range]: ...

    def get_overlap(self, has_region: object) -> int: ...

    def __eq__(self, arg: Range, /) -> bool: ...

    def __le__(self, arg: Range, /) -> bool: ...

    def __lt__(self, arg: Range, /) -> bool: ...

    def __hash__(self) -> int: ...

    @property
    def slug(self) -> str: ...

    def __str__(self) -> str: ...

class Genotype:
    @property
    def alleles(self) -> tuple: ...

    @property
    def is_filtered(self) -> bool: ...

class Variant:
    @property
    def contig(self) -> str: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def num_alleles(self) -> int: ...

    @property
    def num_alts(self) -> int: ...

    @property
    def ref_length(self) -> int: ...

    @property
    def variant_id(self) -> str: ...

    @property
    def has_star_allele(self) -> bool: ...

    def reference_region(self) -> Range: ...

    def record_reference_region(self) -> Range: ...

    def allele_reference_region(self, arg: int, /) -> Range | None: ...

    def allele_length_change(self, arg: int, /) -> int | None: ...

    def allele_length(self, allele_idx: int) -> int | None: ...

    @overload
    def length_change(self) -> list[int | None]: ...

    @overload
    def length_change(self, allele_idx: int) -> int | None: ...

    def allele(self, allele_idx: int) -> str: ...

    def allele_sequence(self, allele_idx: int) -> str | None: ...

    def info_int(self, key: str) -> list[int] | None: ...

    def is_filtered(self) -> bool: ...

    def set_filter_pass(self) -> None: ...

    def has_passing_genotype(self) -> bool: ...

    def subset_samples(self, arg: Sequence[int], /) -> Variant: ...

    def genotype(self, sample_idx: int) -> Genotype: ...

    def __str__(self) -> str: ...

class VariantFileHeader:
    def subset(self, arg: Sequence[str], /) -> VariantFileHeader: ...

class VariantFileReaderIterator:
    def __iter__(self) -> VariantFileReaderIterator: ...

    def __next__(self) -> Variant: ...

class VariantFileReader:
    @staticmethod
    def open(arg: str, /) -> VariantFileReader: ...

    def __enter__(self) -> VariantFileReader: ...

    def __exit__(self, exc_type: object | None = None, exc_value: object | None = None, traceback: object | None = None) -> bool: ...

    @overload
    def fetch(self) -> VariantFileReaderIterator: ...

    @overload
    def fetch(self, region: Range | None = None) -> VariantFileReaderIterator: ...

    def samples(self) -> list[str]: ...

    def header(self) -> VariantFileHeader: ...

    def close(self) -> None: ...

class VariantFileWriter:
    @staticmethod
    def open(filename: str, header: VariantFileHeader, format: str | None = None) -> VariantFileWriter: ...

    def write(self, arg: Variant, /) -> None: ...

    def close(self) -> None: ...

class Graph:
    def __init__(self, arg0: str, arg1: str, arg2: Range, /) -> None: ...

    def save(self, path: str) -> None: ...

    def save_bytes(self) -> bytearray: ...

    @staticmethod
    def load(path: str) -> Graph: ...

    @overload
    @staticmethod
    def load_bytes(data: bytes) -> Graph: ...

    @overload
    @staticmethod
    def load_bytes(data: bytearray) -> Graph: ...

    def node_count(self) -> int: ...

    def has_path(self, arg: str, /) -> bool: ...

    def path_nodes(self, arg: str, /) -> list[int]: ...

    def samples_including(self, arg: Sequence[int], /) -> list[str]: ...

    def dump(self) -> None: ...

    def path_sequence(self, nodes: Sequence[int]) -> str: ...

    @property
    def region(self) -> Range: ...
