_target_: npsv3.models.transformer.MaskedImageModeling
encoder:
  _target_: npsv3.models.transformer.MaskableVisionTransformer
  img_size: 
    - ${pileup.image_height}
    - ${pileup.image_width}
  in_chans: ${len:${pileup.image_channels}}
  use_mask_token: true
  # ViT-B/${data.patch_size} configuration
  patch_size: ${data.patch_size}
  embed_dim: 768
  depth: 12
  num_heads: 12
  num_classes: 0
loss:
  _target_: npsv3.models.transformer.MaskedL1Loss
optimizer:
  _target_: timm.optim.create_optimizer_v2
  _partial_: true
  opt: "adamw"
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.01
scheduler:
  _target_: timm.scheduler.cosine_lr.CosineLRScheduler
  _partial_: true
  lr_min: 0.00001
  t_initial: 5
  cycle_limit: 1
  warmup_t: 5
  warmup_lr_init: 0.0001
  warmup_prefix: true
  
  