ARG BASE_IMAGE=ubuntu:24.04

FROM --platform=$BUILDPLATFORM ${BASE_IMAGE} AS build

RUN apt-get -qq update && apt-get install --no-install-recommends -yq \
  ca-certificates \
  build-essential \
  cmake \
  gdb \
  curl \
  gawk \
  git \
  libbz2-dev \
  libcurl4-openssl-dev \
  libdeflate-dev \
  libjansson-dev \
  libjemalloc-dev \
  liblzma-dev \
  libssl-dev \
  pkg-config \
  protobuf-compiler \
  python3-dev \
  cython3 \
  art-nextgen-simulation-tools \
  bcftools \
  bedtools \
  bwa \
  sambamba \
  samtools \
  tabix \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# Install pip>=25 manually to enable SPDX license identifiers (like used in whatshap)
RUN curl -O https://bootstrap.pypa.io/get-pip.py \
  && python3 get-pip.py --break-system-packages \
  && rm -f get-pip.py

# Download Boost to speed downstream build (just downloading dependencies)
RUN git clone https://github.com/boostorg/boost.git -b boost-1.89.0 /opt/boost --depth 1 \
  && cd /opt/boost \
  && git submodule update --depth 1 -q --init tools/boostdep \
  && git submodule update --depth 1 -q --init libs/flyweight && python3 tools/boostdep/depinst/depinst.py -X test -g "--depth 1" flyweight \
  && git submodule update --depth 1 -q --init libs/hash2 && python3 tools/boostdep/depinst/depinst.py -X test -g "--depth 1" hash2 \
  && git submodule update --depth 1 -q --init libs/scope && python3 tools/boostdep/depinst/depinst.py -X test -g "--depth 1" scope \
  && git submodule update --depth 1 -q --init libs/dynamic_bitset && python3 tools/boostdep/depinst/depinst.py -X test -g "--depth 1" dynamic_bitset \
  && ./bootstrap.sh --prefix=/usr/local \
  && ./b2 \
  && ./b2 install

# Install vg, samblaster and goleft executables
RUN case ${TARGETPLATFORM} in \
    "linux/arm64") VG_DOWNLOAD=vg-arm64 ;; \
    *) VG_DOWNLOAD=vg ;; \
  esac && \
  curl -SL "https://github.com/vgteam/vg/releases/download/v1.67.0/${VG_DOWNLOAD}" \
    -o /usr/local/bin/vg && \
  chmod +x /usr/local/bin/vg

RUN mkdir -p /opt/samblaster && \
  curl -SL https://github.com/GregoryFaust/samblaster/releases/download/v.0.1.26/samblaster-v.0.1.26.tar.gz \
    | tar -xzC /opt/samblaster --strip-components=1 && \
  make -C /opt/samblaster -j $(nproc) && \
  cp /opt/samblaster/samblaster /usr/local/bin/.

RUN case ${TARGETPLATFORM} in \
    "linux/arm64") GOLEFT_DOWNLOAD=goleft_linux_aarch64 ;; \
    *) GOLEFT_DOWNLOAD=goleft_linux64 ;; \
  esac && \
  curl -SL "https://github.com/brentp/goleft/releases/download/v0.2.6/${GOLEFT_DOWNLOAD}" \
    -o /usr/local/bin/goleft && \
  chmod +x /usr/local/bin/goleft

# Install odgi (and libraries) During development we are mounting our local fork of odgi into the container
RUN git clone --depth 1 --recursive --branch node_del https://github.com/mlinderm/odgi.git /opt/odgi \
  && cmake -S /opt/odgi -B /opt/odgi/build -DBUILD_STATIC=1 \
  && cmake --build /opt/odgi/build -- -j $(nproc) \
  && cp /opt/odgi/bin/odgi /usr/local/bin \
  && cp /opt/odgi/lib/odgi.*.so /usr/local/lib  

# Force "Unix Makefiles" instead of Ninja due to issues with ExternalProject_Add download and build
ENV CMAKE_GENERATOR="Unix Makefiles" \
  CMAKE_INCLUDE_PATH="/opt/odgi/src:${CMAKE_INCLUDE_PATH}" \
  CMAKE_LIBRARY_PATH="/opt/odgi/fork/build/handlegraph-prefix/lib:/opt/odgi/lib:${CMAKE_LIBRARY_PATH}" \
  LD_PRELOAD="/lib/aarch64-linux-gnu/libjemalloc.so:${LD_PRELOAD}" \
  PYTHONPATH="/usr/local/lib:${PYTHON_PATH}"

# Install hatch for development (seems to be a regression in 1.16.3)
RUN python3 -m pip install --break-system-packages --no-cache-dir \
  hatch==1.16.2

ADD . /opt/npsv3

WORKDIR /opt/npsv3

# Install the package as a user (to prepare for multistage build), preferentially installing PyTorch
# from the CPU-only wheel since we are targeting aarch64
ENV PATH=/root/.local/bin:$PATH
RUN python3 -m pip install --user --break-system-packages --no-cache-dir \
  --index-url https://download.pytorch.org/whl/cpu \
  --extra-index-url https://pypi.org/simple/ \
  .



# TODO: Multistage build to reduce image size and avoid installing build dependencies in the final image
# Adapted from: https://pythonspeed.com/articles/multi-stage-docker-python/
# FROM --platform=$BUILDPLATFORM ${BASE_IMAGE}

# # Copy installed Python packages, libraries and binaries
# COPY --from=build /root/.local /root/.local
# COPY --from=build /usr/local/bin/vg /usr/local/bin/samblaster /usr/local/bin/goleft /usr/local/bin

# RUN apt-get -qq update && apt-get install --no-install-recommends -yq \
#   art-nextgen-simulation-tools \
#   bcftools \
#   bedtools \
#   bwa \
#   sambamba \
#   samtools \
#   tabix \
#   && \
#   apt-get clean -y && \
#   rm -rf /var/lib/apt/lists/*

# ENV PATH=/root/.local/bin:$PATH
# CMD ["npsv3"]