ARG BASE_IMAGE=ubuntu:22.04

FROM --platform=$BUILDPLATFORM ${BASE_IMAGE}

RUN apt-get -qq update && apt-get install --no-install-recommends -yq \
  art-nextgen-simulation-tools \
  bcftools \
  bedtools \
  build-essential \
  bwa \
  ca-certificates \
  cmake \
  curl \
  gawk \
  git \
  libbz2-dev \
  libjemalloc-dev \
  liblzma-dev \
  libsdsl-dev \
  pkg-config \
  protobuf-compiler \
  python3-dev \
  python3-distutils \
  python3-pip \
  python3-pkgconfig \
  sambamba=0.8.2+dfsg-2 \
  samtools \
  tabix \
  && \
  apt-get clean -y && \
  rm -rf /var/lib/apt/lists/*

# Install vg
RUN case ${TARGETPLATFORM} in \
    "linux/arm64") VG_DOWNLOAD=vg-arm64 ;; \
    *) VG_DOWNLOAD=vg ;; \
  esac && \
  curl -SL "https://github.com/vgteam/vg/releases/download/v1.54.0/${VG_DOWNLOAD}" \
    -o /usr/local/bin/vg && \
  chmod +x /usr/local/bin/vg

# Install odgi (and libraries)
# RUN mkdir -p /opt/odgi \
#   && curl -SL https://github.com/pangenome/odgi/releases/download/v0.8.3/odgi-v0.8.3.tar.gz \
#   | tar -xzC /opt/odgi --strip-components=1 \
#   && cmake -S /opt/odgi -B /opt/odgi/build \
#   && cmake --build /opt/odgi/build -- -j 2

# During development we are mounting our local fork of adgi into the containter

# Needed for odgi Python bindings
ENV LD_PRELOAD="/lib/aarch64-linux-gnu/libjemalloc.so:${LD_PRELOAD}" \
  PYTHONPATH="/opt/odgi/lib:${PYTHON_PATH}" \
  PATH="/opt/odgi/bin:${PATH}"

RUN mkdir -p /opt/samblaster && \
    curl -SL https://github.com/GregoryFaust/samblaster/releases/download/v.0.1.26/samblaster-v.0.1.26.tar.gz \
      | tar -xzC /opt/samblaster --strip-components=1 && \
    make -C /opt/samblaster && \
    cp /opt/samblaster/samblaster /usr/local/bin/.

RUN case ${TARGETPLATFORM} in \
      "linux/arm64") GOLEFT_DOWNLOAD=goleft_linux_aarch64 ;; \
      *) GOLEFT_DOWNLOAD=goleft_linux64 ;; \
    esac && \
    curl -SL "https://github.com/brentp/goleft/releases/download/v0.2.6/${GOLEFT_DOWNLOAD}" \
      -o /usr/local/bin/goleft && \
    chmod +x /usr/local/bin/goleft

ADD . /opt/npsv3

RUN pip install --upgrade pip

# Install pytorch from CPU-only wheel
RUN python3 -m pip install --no-cache-dir \
  --extra-index-url https://download.pytorch.org/whl/cpu/ \
  torch torchvision torchaudio
       
# Install hatch for development
RUN python3 -m pip install --no-cache-dir \
  hatch

WORKDIR /opt/npsv3

RUN python3 -m pip install --no-cache-dir .