# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cachang/npsv3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cachang/npsv3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cachang/npsv3/CMakeFiles /home/cachang/npsv3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cachang/npsv3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named seqlib

# Build rule for target.
seqlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 seqlib
.PHONY : seqlib

# fast build rule for target.
seqlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seqlib.dir/build.make CMakeFiles/seqlib.dir/build
.PHONY : seqlib/fast

#=============================================================================
# Target rules for targets named _native

# Build rule for target.
_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _native
.PHONY : _native

# fast build rule for target.
_native/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_native.dir/build.make CMakeFiles/_native.dir/build
.PHONY : _native/fast

src/npsv3/bindings.o: src/npsv3/bindings.cpp.o
.PHONY : src/npsv3/bindings.o

# target to build an object file
src/npsv3/bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_native.dir/build.make CMakeFiles/_native.dir/src/npsv3/bindings.cpp.o
.PHONY : src/npsv3/bindings.cpp.o

src/npsv3/bindings.i: src/npsv3/bindings.cpp.i
.PHONY : src/npsv3/bindings.i

# target to preprocess a source file
src/npsv3/bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_native.dir/build.make CMakeFiles/_native.dir/src/npsv3/bindings.cpp.i
.PHONY : src/npsv3/bindings.cpp.i

src/npsv3/bindings.s: src/npsv3/bindings.cpp.s
.PHONY : src/npsv3/bindings.s

# target to generate assembly for a file
src/npsv3/bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_native.dir/build.make CMakeFiles/_native.dir/src/npsv3/bindings.cpp.s
.PHONY : src/npsv3/bindings.cpp.s

src/npsv3/realigner.o: src/npsv3/realigner.cpp.o
.PHONY : src/npsv3/realigner.o

# target to build an object file
src/npsv3/realigner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_native.dir/build.make CMakeFiles/_native.dir/src/npsv3/realigner.cpp.o
.PHONY : src/npsv3/realigner.cpp.o

src/npsv3/realigner.i: src/npsv3/realigner.cpp.i
.PHONY : src/npsv3/realigner.i

# target to preprocess a source file
src/npsv3/realigner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_native.dir/build.make CMakeFiles/_native.dir/src/npsv3/realigner.cpp.i
.PHONY : src/npsv3/realigner.cpp.i

src/npsv3/realigner.s: src/npsv3/realigner.cpp.s
.PHONY : src/npsv3/realigner.s

# target to generate assembly for a file
src/npsv3/realigner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_native.dir/build.make CMakeFiles/_native.dir/src/npsv3/realigner.cpp.s
.PHONY : src/npsv3/realigner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... seqlib"
	@echo "... _native"
	@echo "... src/npsv3/bindings.o"
	@echo "... src/npsv3/bindings.i"
	@echo "... src/npsv3/bindings.s"
	@echo "... src/npsv3/realigner.o"
	@echo "... src/npsv3/realigner.i"
	@echo "... src/npsv3/realigner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

