[pytest]
markers =
  cfg_overrides
filterwarnings =
    error
    ignore:The value of the smallest subnormal for <class 'numpy.float(32|64)'> type is zero.:UserWarning:numpy
    ignore:pkg_resources is deprecated as an API:DeprecationWarning
    ignore:DeprecationWarning. local mode is an experimental feature that is no longer maintained:DeprecationWarning
    ignore: subprocess (\d+) is still running:ResourceWarning
    ignore:unclosed file <_io.TextIOWrapper name='/tmp/ray/[a-zA-Z0-9_-]+/logs/[a-zA-Z0-9_-]+.(err|out)' mode='a' encoding='utf-8'>:ResourceWarning
testpaths = 
    tests